filetype plugin indent on

" Syntax highlight "
syntax on 

" Make vim incompatible to vi "
set nocompatible
set modelines=0

" Tab settings "
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" More Common Settings "
set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell

set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2

" Set relativenumber "
set number
set norelativenumber

" Set undofile "
set shell=/bin/bash
set lazyredraw
set matchtime=3

" Change Leader Key "
let mapleader=","

" Dictionary Path "
set dictionary="/usr/share/dict/words"

" Enable mouse "
set mouse=a

" Enable Solarized Theme "
set t_Co=256
set background=dark
let g:solarized_termcolors=256
let g:solarized_visibility="high"
let g:solarized_contrast="high"
"" transparent configuration
" let g:solarized_termtrans=1
colorscheme solarized 

" Airline Configuration "
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_section_y='BN: %{bufnr("%")}'

" Ctrl P Configuration "
let g:ctrlp_show_hidden=1

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'git://git.wincent.com/command-t'
Plugin 'kien/ctrlp.vim'
Plugin 'plasticboy/vim-markdown'
Plugin 'bling/vim-airline'
Plugin 'scrooloose/nerdtree'
Plugin 'altercation/vim-colors-solarized'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'pangloss/vim-javascript'
Plugin 'scrooloose/syntastic'
call vundle#end()

" Map keys
map <C-n> :NERDTreeToggle<CR>
map <C-p> :CtrlP<CR>

nnoremap (b :bp<CR>
nnoremap )b :bn<CR>
