set nu

set nocompatible
filetype off

syntax on 
let g:solarized_termcolors=256
set t_Co=256
set background=dark
colorscheme solarized

let g:airline#extensions#tabline#enabled = 1
set laststatus=2

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'git://git.wincent.com/command-t.git'
Plugin 'git@github.com:kien/ctrlp.vim.git'
Plugin 'git@github.com:scrooloose/nerdtree.git'


Plugin 'git@github.com:plasticboy/vim-markdown.git'
Plugin 'bling/vim-airline.git'
Plugin 'git@github.com:altercation/vim-colors-solarized.git'

call vundle#end()
filetype plugin indent on

" Map keys

map <C-n> :NERDTreeToggle<CR>
map <C-p> :CtrlP<CR>
